openapi: 3.0.1
info:
  title: Interlok Workflow REST services
  description: A REST entry point into your Interlok workflows.
  version: "1.0"
servers:
  - url: 'http://localhost:8080'
paths:
  /workflow-services/MyInterlokInstance/Channel-1/Workflow-1:
    post:
      description: Inject your data directly into any one of your Interlok Workflows.  Simply change the url to your Interlok host, set headers to be mapped into Interlok metadata and POST your body data.
      requestBody:
        content:
          text/plain:
            schema:
              type: string
            examples:
              '0':
                value: Some body
      responses:
        '200':
          description: The resulting message after being processed by your target Interlok workflow.
          content:
            text/plain:
              schema:
                type: string
              examples:
                '0':
                  value: Some body